### ISSUE TITLE
feature request: option for single-line tags (no newline)

### ISSUE THREAD

**Issue by dwhieb** [atom/autocomplete-html#10]
It would be great to have an option for tags to be autocompleted without newlines. So instead of tab producing this:

```
<p>
    [cursor]
</p>
```

it would instead produce this:

```
<p>[cursor]</p>
```

**Comment by jeffdaley** [comment]
I'd also like this option.

**Comment by 50Wliu** [comment]
This has since been fixed (and was an issue with language-html's snippets, not autocomplete-html).
