### ISSUE TITLE
Recommendations disappear immediately

### ISSUE THREAD

**Issue by Kyoushin** [atom/autocomplete-html#11]
So my issue is, i can't make any use of this since the recommendations disappear immediately and i can't even move to any of them with arrow keys.

**Comment by benogle** [comment]
Can you make a gif?

Please quit atom completely and run `atom --safe`. Is the issue still there?

**Comment by Kyoushin** [comment]
http://makeagif.com/q1wOiJ 
there i try to move down with arrow keys, but as you see it ends me up on the next line, ill try to run that

**Comment by Kyoushin** [comment]
issue fixed by running it on safemode once

**Comment by 50Wliu** [comment]
Ok, thanks for letting us know @Kyoushin :smile:.
