### ISSUE TITLE
HTML Entities Autocomplete

### ISSUE THREAD

**Issue by cakebake** [atom/autocomplete-html#14]
Should this package automatically suggest HTML Entities like `&nbsp;`, `&amp;`, `&uuml;`, ..., or would that be the task of other packages?

**List:** https://github.com/adobe/brackets/blob/master/src/extensions/default/HtmlEntityCodeHints/SpecialChars.json

**Comment by benogle** [comment]
Yeah, this seems like a reasonable addition to this package. PRs welcome :)

**Comment by cakebake** [comment]
Ok, I just have to look at the structure for the autocomplete :+1:

**Comment by jeancroy** [comment]
Maybe as snippet for the HTML language ?
https://github.com/atom/language-html/blob/master/snippets/language-html.cson

**Comment by cakebake** [comment]
@jeancroy atom/language-html#87

**Comment by scarecrow21** [comment]
Hi. I'm a newbie and would like to fix my first open source bug. Would someone please help me go about fixing this bug?

**Comment by Aerijo** [comment]
@scarecrow21 The completions are defined in the file `completions.json`. You can look at  `lib/provider.coffee` to see how these completions are parsed and turned into suggestions. 

As this package is like an 'add-on' for [`autocomple-plus`](https://github.com/atom/autocomplete-plus) I also suggest reading about the [provider API](https://github.com/atom/autocomplete-plus/wiki/Provider-API) to familiarise yourself with how this all works.

**Comment by guozhaonan** [comment]
Hi, is this issue still open? I'd love to write a fix if it is :)

**Comment by LuizGyro** [comment]
Hi, I'd like to try to fix this one as my first contribution. Is this one still beginner-friendly? Thank you!

**Comment by Fwalsh96** [comment]
Does it matter where these entities are inserted in the completions.json file?

**Comment by TheOtterlord** [comment]
@Fwalsh96 Yes. If they are placed in the tag section, they will be autocompleted as tags. If they are in the attribute section, they will be autocompleted as attributes. I think you would need to add another section and add to the js code to complete them correctly
