### ISSUE TITLE
Format of autocompleted boolean HTML attributes

### ISSUE THREAD

**Issue by benogle** [atom/autocomplete-html#15]
_From @willnwhite on November 15, 2015 11:52_

E.g. checked is a true/false checkbox attribute, and rather than Atom autocompleting to `checked=""`, implying checked takes a value, it should just complete to `checked`, implying true. I had to read the HTML spec to learn that the actual presence or absence of boolean attributes were their true and false values, and Atom did not help me learn this (for ages I was trying `checked="false"` to no avail).

_Copied from original issue: atom/autocomplete-plus#613_

**Comment by benogle** [comment]
Thanks for the report. Def a bug

**Comment by willnwhite** [comment]
I went off to try to fix this myself but ended up in Brackets' Freenode channel with no reply. Could you outline how I could fix this for us and I'll try again?

**Comment by benogle** [comment]
Looks like this is on our side, not the JSON file's issue. There is a `type` flag attribute on those options (see [the JSON](https://raw.githubusercontent.com/adobe/brackets/master/src/extensions/default/HTMLCodeHints/HtmlAttributes.json)), and we are not handling it.

```js
"checked": { "attribOption": [], "type": "flag" }
```

I'd follow [this function](https://github.com/atom/autocomplete-html/blob/f2d6f1cbcfcd3ba7890940582d5d2a7056591dab/lib/provider.coffee#L95) up and figure out where to check the `type` attr.

**Comment by willnwhite** [comment]
By "[this function](https://github.com/atom/autocomplete-html/blob/f2d6f1cbcfcd3ba7890940582d5d2a7056591dab/lib/provider.coffee#L95)" I guess you mean `buildTagCompletion`, but I can't see what to do with that. Isn't [`buildAttributeCompletion`](https://github.com/atom/autocomplete-html/blob/f2d6f1cbcfcd3ba7890940582d5d2a7056591dab/lib/provider.coffee#L113) the one to go after, specifically the `snippet:` value? And [on master](https://github.com/atom/autocomplete-html/blob/master/lib/provider.coffee#L113), or not?

I'm new (perhaps you can tell). I'm using Atom a lot and naturally I'd like to learn how to patch it up as I notice things. Thanks for your help so far. I'm trying to set up the development environment, following the official instructions for Atom and packages, but I've got stuck.

I cloned Atom and used [`script/build`](https://github.com/atom/atom/blob/master/docs/build-instructions/os-x.md) (OS X) to successfully build it. Editing the autocomplete-html provider.coffee source file and rebuilding made no difference. I tried:

```coffeescript
  buildAttributeCompletion: (attribute, tag) ->
    if tag?
      snippet: if attribute.type is 'flag' then attribute else "#{attribute}=\"$1\"$0" # duplicate in else
      displayText: attribute
      type: 'attribute'
      rightLabel: "<#{tag}>"
      description: "#{attribute} attribute local to <#{tag}> tags"
      descriptionMoreURL: @getLocalAttributeDocsURL(attribute, tag)
    else
      snippet: if attribute.type is 'flag' then attribute else "#{attribute}=\"$1\"$0" # duplicate in if
      displayText: attribute
      type: 'attribute'
      description: "Global #{attribute} attribute"
      descriptionMoreURL: @getGlobalAttributeDocsURL(attribute)
```

autocomplete-html is enabled in Settings.

**Comment by benogle** [comment]
> By "this function" I guess you mean buildTagCompletion

Sorry, you're right: `buildAttributeCompletion`. I fixed the link.

You will need to fork the package, and do your work on the fork. Making a branch on your fork is good. Then when you get it working, and have tests, make a PR.
