### ISSUE TITLE
Include equals and quotes when autocompleting attributes

### ISSUE THREAD

**Issue by djch** [atom/autocomplete-html#2]
I'm very accustomed to Coda autocompleting attributes like `class` with the equals and quotes included (and the cursor between the quotes).

Having to type <kbd>=</kbd>, <kbd>"</kbd>, every single time is super bumming me out and would love if the autocomplete package could rescue me from this.

Actually, I suppose there are some attributes which don't require parameters like `disabled` and what-not. So maybe this should be for those that commonly do, like: `class`, `id`, `href`, `target`, `alt`, `title`, `src` ... okay there are heaps.

Or maybe it could be a toggle in the package settings. Or maybe it should just apply to all attributes because they have parameters more often than they don't.

**Comment by thegumbyman** [comment]
:+1:

**Comment by djch** [comment]
A wild GIF appears:
![screen recording 2015-04-16 at 12 44 pm](https://cloud.githubusercontent.com/assets/4392286/7173173/96724e52-e436-11e4-8582-7c2d50041ed4.gif)

**Comment by benogle** [comment]
Yeah, they should be snippets.

**Comment by djch** [comment]
Looks like the v0.6.0 update implements this in an awesome way. Thanks @benogle! :heart: :sparkles:

**Comment by benogle** [comment]
Forgot about this. closing

**Comment by benogle** [comment]
Also, after you get done typing the attribute value, you can hit tab to get out of the quotes. Yay snippets.
