### ISSUE TITLE
Is there a setting to autocomplete with ending tags? 

### ISSUE THREAD

**Issue by mvaneijgen** [atom/autocomplete-html#22]
I have made a screengrap of me struggling to type a `div`. It is second nature now to just start typing what I want and let the code editor finish, but in Atom it only autocompletes your tag when you don't start with a `<` which is really frustrating cause every tag starts with a `<`. 

![screengrap](http://i.imgur.com/yzKHhFV.gif)

Could we get a setting that autocompletes the tag like we get when we don't `<` 
I think these are from the `autocomplete-snippets package.`

It would also be nice to don't hide the dropdown window when a tag is finished typed, because some tags are just really short like a `div` or `p`, so we still can hit enter to complete the tag.

**Comment by patrick96** [comment]
The feature you describe (without using `<`) is from the package `language-html` and they are just simple snippets.
You could try create your own snippet where the prefix is `<div`, I haven't been able to do this yet and I don't know why. Maybe you'll have some better luck.

**Comment by lee-dohm** [comment]
There is not a setting for what you're asking. The main reason behind this is that the snippets package has issues with snippet triggers that include non-word characters, see https://github.com/atom/snippets/issues/151.
