### ISSUE TITLE
not working properly as it'll perform.........

### ISSUE THREAD

**Issue by Aakash30Sethiya** [atom/autocomplete-html#24]
when i start a tag with coding..... {Just an Example.....}
<he
it gives me suggestions
i choose one of them and press enter 
it shows only

<head

now tell me what is this ?

actually it perform like that when i press enter it'll complete like this......

<head>
      |  {with the cursor blinking in the middle of the starting tag and the end tag}
</head>

if this pakage doesn't work like that, 
then please tell me the pakage name which perform like that.........
thanks in advance........

**Comment by revelt** [comment]
May I suggest, don't start typing `<`, type tag straight away, then press `tab` key. Type: `head`, click `tab`.

Please update on the status of this ticket, do you still need help or can we close it.

**Comment by Aakash30Sethiya** [comment]
ok thanks............
you may proceed to close this report.......0:)

**Comment by revelt** [comment]
Would you like to close the ticket yourself?
