### ISSUE TITLE
Autocomplete suggests tags instead of attributes

### ISSUE THREAD

**Issue by Tathanen** [atom/autocomplete-html#25]
If you type a tag, put the cursor at the end, and hit space, you get an autocomplete list for attributes.  You can start typing, it'll narrow down the list, everything works great.

If you place the cursor inside a tag that already has an attribute, before that attribute, and hit space, you get an autocomplete list for attributes as expected.  When you start to type, though, the autocomplete list turns into a list of tags, not attributes.

If you place the cursor at the end of this tag and hit space everything works fine, this only happens if you bring up the autocomplete inside a tag before an already-existing attribute.

**Comment by 50Wliu** [comment]
Sample code:
```html
<select | autofocus 
```
where `|` is the cursor.

**Comment by Tathanen** [comment]
:+1:

**Comment by 50Wliu** [comment]
Sorry for the time it took to get this fixed.  It should be available starting in Atom 1.18.0.
