### ISSUE TITLE
Feature request: autocomplete some attributes without auto-quotes

### ISSUE THREAD

**Issue by Tathanen** [atom/autocomplete-html#26]
In HTML5 you can add things like `disabled` and `required` to tags without having to write `disabled="disabled"` or `required="required"`.  Auto-completing these attributes, however, adds the`=""` every time.  It would be great to have a setting we could toggle to allow these stand-alone attributes to auto-complete without the quotes.

**Comment by Tathanen** [comment]
This may be a duplicate of https://github.com/atom/autocomplete-html/issues/15 actually, apologies!

**Comment by 50Wliu** [comment]
Yeah, this seems similar enough to #15.
