### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by ghost** [atom/autocomplete-html#27]
I'm So Sorry !!! It does work. It's perfect and it's amazing that you actually came to help !! :D

**Comment by thomasjo** [comment]
Please provide more details. As it stands, this issue doesn't make any sense. There is zero information beyond "does not work".

**Comment by 50Wliu** [comment]
> I'm So Sorry !!! It does work. It's perfect and it's amazing that you actually came to help !! :D

Issue body has been updated since creation, so closing.
