### ISSUE TITLE
How can we enable this in other filetypes? (e.g. handlebars)

### ISSUE THREAD

**Issue by Redsandro** [atom/autocomplete-html#31]
I was looking for something I can add to my own init script, or a piece of source code for which I can create a PR. After snooping around, I concluded that I'm too new to Atom to figure it out.

There should be something like `fileTypes` containing `['htm', 'html']`, which would be a good place to add `['hbs', 'hdbs', 'handlebars']`.

This is thinking too simple, no?

[This issue](https://github.com/atom/autocomplete-html/issues/16) is probably about the same.

**Comment by lee-dohm** [comment]
The autocomplete provider currently [looks for the scope of `.text.html` to activate.](https://github.com/atom/autocomplete-html/blob/master/lib/provider.coffee#L9) What this means is that in any location, in any language, that is matches `.text.html`, this provider will be enabled automatically. This is why the provider works in HTML files (`.text.html`), PHP files (`.text.html.php` for the sections which are recognized as HTML) and even in Markdown files that have code blocks marked as HTML. (See below for an example.)

So if the handlebars language definition declares the handlebars scope as `.text.html.handlebars` or something similar, the HTML autocomplete provider will start working automatically.

(Paste the text below the divider line into a markdown file and try it out!)

-----

```html
<!-- If you type something in the blank line below, you'll see the HTML autocomplete provider suggestions appearing. -->

```

**Comment by Redsandro** [comment]
Oh nice, this is sweet. Thanks for the elaborate response @lee-dohm!
