### ISSUE TITLE
Autocomplete don't suggests some atribbutes values

### ISSUE THREAD

**Issue by lukalazov** [atom/autocomplete-html#37]
I made an issue to autocomplete-html about "Suggestions for atribute 'type' in input". you can read it [here](https://github.com/atom/autocomplete-html/issues/35). 

And while I read the README file I found out that autocomplete-html is powered by a list of HTML tags and HTML attributes from Brackets HTMLCodeHints. 

So I headed there and saw the suggestion that I was asking for in  "Suggestions for atribute 'type' in input", but they are not showing up in autocomplete. 

This is only occurring in attributes that have the `/`, for example `input/type` or `button/type`.

![screenshot from 2016-06-30 18-50-14](https://cloud.githubusercontent.com/assets/19621015/16497021/3e133f30-3ef5-11e6-9373-06696a24c3cb.png)

**Comment by chrisgriffith** [comment]
The issue is in this line of code from update.coffee:
delete attributes[attribute] if attribute.indexOf('/') isnt -1
I have not had a chance to look further into the why or the fix.

**Comment by lukalazov** [comment]
Do you know how to fix this? 
Because I am really not a programmer.

**Comment by iampepe** [comment]
Anyone working on the fix?
