### ISSUE TITLE
Show attribute value autocompletions without having to autocomplete the attribute

### ISSUE THREAD

**Issue by pinkdoremi** [atom/autocomplete-html#38]
It does not like the demo in Readme.md

when the text is:

```
<meta charset=>
```

and **THEN** I type one `"` , it becomes:

```
<meta charset="">
```

But there is no suggestion!

**Comment by geligelu** [comment]
I get this too.

For example:  ``<style type="">...`` should show ``text/css`` as a suggestion for the attribute, but it just doesn't show at all...

Checking [here (the list of attributes listed in the project readme.md](https://github.com/adobe/brackets/blob/master/src/extensions/default/HTMLCodeHints/HtmlAttributes.json), it should be available:
````
...
"style/type":         { "attribOption": ["text/css"] },
...
````

Any thoughts?

**Comment by 50Wliu** [comment]
@pinkdoremi If you look at the gif, the autocompletion only happens when you autocomplete the `charset` attribute.  Though I agree, the autocompletions should show up even if you type `charset="` manually.
