### ISSUE TITLE
html element tag icon not being displayed

### ISSUE THREAD

**Issue by metasean** [atom/autocomplete-html#42]
In the README's animated gif html elements, attributes, and attribute values have distinct visual tags.  

My installation does not have the element tags, but does have attribute and attribute value tags.  Instead of element tags it has the green tab right tag.

| Working as expected: | Not working:  | instead get:  |
|-----------------------|--------------|--------------|
| ![](https://gist.githubusercontent.com/metasean/31243bacdd91e21374f062c0e7a7857f/raw/ce2ee69b833b31557ba232302b4699e1b3245081/html-attribute-tag.png) , ![](https://gist.githubusercontent.com/metasean/31243bacdd91e21374f062c0e7a7857f/raw/ce2ee69b833b31557ba232302b4699e1b3245081/html-attribute-value-tag.png) | ![](https://gist.githubusercontent.com/metasean/31243bacdd91e21374f062c0e7a7857f/raw/ce2ee69b833b31557ba232302b4699e1b3245081/html-element-tag.png) | ![](https://gist.githubusercontent.com/metasean/31243bacdd91e21374f062c0e7a7857f/raw/0d50889813bc3543c7a34c40de03f223b4086d53/generic-autocomplete-tag.png) |

autocomplete-html: 0.7.2
atom: 1.12.2 & 1.12.4
seen with: Atom Dark, Base 16 Tomorrow Dark, One Dark, & Solarized Dark

**Comment by 50Wliu** [comment]
You need to type the `<` first as shown in the gif.
