### ISSUE TITLE
Please add this attributes for autocomplete-html table

### ISSUE THREAD

**Issue by matijasss** [atom/autocomplete-html#45]
Could you please add "cellpadding" and "cellspacing" attributes to the tag table in the html-autocomplete package.

**Comment by 50Wliu** [comment]
Please ask Brackets to update the HTML attributes file that we use to generate attribute autocompletions: https://github.com/adobe/brackets/blob/master/src/extensions/default/HTMLCodeHints/HtmlAttributes.json
