### ISSUE TITLE
autocomplete-html is deprecated

### ISSUE THREAD

**Issue by WalterBrito** [atom/autocomplete-html#54]
You have the core package "autocomplete-html" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.

**Comment by rsese** [comment]
See the error message for details on how to resolve this problem:

> You have the core package "autocomplete-html" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
