### ISSUE TITLE
Template Engines

### ISSUE THREAD

**Issue by amiuhle** [atom/autocomplete-html#7]
Any plans to extend this to support template engines like [Slim](http://slim-lang.com/) or [Jade](http://jade-lang.com/), or should that be implemented in separate packages?

**Comment by 50Wliu** [comment]
@amiuhle would [language-jade](https://atom.io/packages/language-jade) or [language-slim](https://atom.io/packages/language-slim) suffice?

**Comment by 50Wliu** [comment]
This should be implemented by separate packages.
