### ISSUE TITLE
autocomplete-html does not working

### ISSUE THREAD

**Issue by kikesoide** [atom/autocomplete-html#70]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

autocomplete-html does not working

### Steps to Reproduce

1. writing some tag of html
2. Ctrl + space
3. nothing

**Expected behavior:** [What you expect to happen]
popup with options for autocomplete

**Actual behavior:** [What actually happens]
I don't see any option
**Reproduces how often:** [What percentage of the time does it reproduce?]
every time
### Versions

1.17.0 X64 update 
### Additional Information
Windows 10

**Comment by 50Wliu** [comment]
> writing some tag of html

Please describe exactly what you're typing.

**Comment by kikesoide** [comment]
I just realized that if the file is not '.html', the autocomplete function
does not work :P

sorry

*--*

*Jorge Enrique Torres Esquivel*

*Ingeniero de sistemas y computación -UPTC*

*Especialista en Ingenieria de Software - U- DistritalAnalista Senior-
Subdirección de Desarrollo de Aplicaciones - ICFES*
* <http://www.icfes.gov.co>*


2017-05-22 23:08 GMT-05:00 Wliu <notifications@github.com>:

**Comment by 50Wliu** [comment]
Haha, no worries!  Happens to the best of us :grinning:.
