### ISSUE TITLE
HTML Autocomplete package not working

### ISSUE THREAD

**Issue by smuko** [atom/autocomplete-html#73]
HTML Autocomplete package not working in the package installer it says that the package is installed but it dsnt work.it dsnt suggest anything

**Comment by smuko** [comment]
HTML Autocomplete package not working in the package installer it says that the package is installed but it dsnt work.it dsnt suggest anything

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by smuko** [comment]
im very new to coding world can u explain what u mean by the template?

**Comment by 50Wliu** [comment]
Sure, when creating a new issue you should see the following:
```
<!--

Have you read Atom's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md

Do you want to ask a question? Are you looking for support? The Atom message board is the best place for getting support: https://discuss.atom.io

-->

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
```

just fill out as much as you can before creating the issue.

**Comment by smuko** [comment]
### Description

when i try to write html code it suppos to sujest me tags
for example if i write <html it suppos to suggest me the
whole tag as <html></html> which is not happening at all

### Steps to Reproduce

1. [First Step]
    open atom
2. [Second Step]
    try to write html or any code

3. [third step]
    its not suggesting any similar code at all


 **Expected behavior:** [if i write any code it suppos to suggest me
similar codes ]

 **Actual behavior:** [its not suggesting any codes at all]

**Reproduces how often:** [it happens all the time]

### Versions

im using atom 1.14.4 64bit in windows seven

### Additional Information

it would be verry helpfull if u tell me how can i uninstall atom
completly and install it from new version.
i did tried to reinstalling atom but the problem remains same

**Comment by 50Wliu** [comment]
The way autocomplete-html works is that it suggests completions as you type it.  For example, if you type `<htm`, then it'll suggest `html` but _not_ `<html></html>`.  See this GIF for more information:
![autocomplete-html](https://cloud.githubusercontent.com/assets/2766036/25668197/ffd24928-2ff3-11e7-85fc-b327ac2287e6.gif)

Of course, this is also something that can be added in the future, but it's not a priority right now.

**Comment by 50Wliu** [comment]
You can reinstall Atom by downloading the installer at https://atom.io.

**Comment by smuko** [comment]
ty so much for the help but i have 1 last thing to ask iv seen plenty of
cideos in youtube that when someone types<!DOCTYPE html>
atom suggests the whole html tag with head body etc how i can do that? and
sorry about my broken english

**Comment by 50Wliu** [comment]
Type: `html` (without the opening bracket) and then press <kbd>tab</kbd>.

**Comment by smuko** [comment]
as i said its not working when i press tab it just go right and make space
as spacebar works 😫

**Comment by beauregardie** [comment]
save file with an extension , ex:  site_1.php for auto-complete  to work

**Comment by ikeshav** [comment]
Hey, I was facing the same problem recently but I got the solution.

I figured the problem was with my file extension. I created a .txt file and named it <file name>.html thinking it would change to a html file. But it does not. Follow these steps:

1. Open a new file in atom (Ctrl+N).
2. Save the file(Ctrl+S) with a .html at the extension(end). It will surely work.

Thank You
