### ISSUE TITLE
Enchance/Fix autocomplition of the hidden html attribute

### ISSUE THREAD

**Issue by dagolinuxoid** [atom/autocomplete-html#75]
### Description
hidden html attribute has a wrong/redundant autocompletion
### Steps to Reproduce

1. &lt;p>&lt;/p>
2. &lt;p hi>&lt;/p>
3. press tab
3. &lt;p hidden="">&lt;/p>

**Expected behavior:** after press tab I expected to see just &lt;p hidden>&lt;/p>

**Actual behavior:** &lt;p hidden="">&lt;/p>

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.19.0
apm  1.18.2
OS: Elementary OS 0.3.2 Freya (64-bit) built on Ubuntu 14.04
```

### Additional Information
So `hidden` attribute should behave as correctly as `reversed` attribute on autocomplition, but 
at this point it behaves as a regular attribute — `class` for example.

**Comment by abaracedo** [comment]
This is fixed in https://github.com/adobe/brackets/pull/13752

**Comment by dagolinuxoid** [comment]
@abaracedo due to my third world crappy PC which I'm having currently  I've moved entirely to blazingly fast neovim  anyway :)

**Comment by 50Wliu** [comment]
Thanks @abaracedo!  It'll be picked up in the next upstream sync which should happen in the next few days.
