### ISSUE TITLE
Close previous tag when type </

### ISSUE THREAD

**Issue by kritsky** [atom/autocomplete-html#9]
Is there any way to do that?

**Comment by mnquintana** [comment]
You can close a tag in an HTML document with <kbd>Cmd-Alt-.</kbd> (or <kbd>Ctrl-Alt-.</kbd> on Windows and Linux) – does that about cover what you're looking for?

**Comment by kritsky** [comment]
Yes. But it is better to type <kbd></</kbd> like in sublime. No need to <kbd>cmd+alt+.</kbd> just <kbd></</kbd> and that's it. Simplier

**Comment by mnquintana** [comment]
This is actually a duplicate of https://github.com/atom/language-html/issues/63 – please subscribe there for updates.

**Comment by kritsky** [comment]
thank you
